/**
 * Generates the SYNTHETIC seed data in data/.
 *
 * Run: node tools/generate-data.mjs
 *
 * - Seeded PRNG, so output is identical on every run (a unit test checks this).
 * - Randomness exists ONLY here, at build time. The app never calls Math.random().
 * - Values are illustrative. They are NOT measurements from Inukjuak or any real household.
 */
import { writeFile, mkdir, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const STEP_MIN = 30;
const HOURS = 48;
const N = (HOURS * 60) / STEP_MIN + 1; // 97 readings per household
const LITRES_PER_PERSON_DAY = 60;
// Nominal end of the recording. The app replays the recording relative to when it is first opened.
const END = new Date(Date.UTC(2026, 8, 26, 12, 42));
const SYNTHETIC_NOTE =
  'SYNTHETIC SAMPLE DATA generated by tools/generate-data.mjs for a hackathon prototype. Not real measurements. No household water-quality data from Inukjuak is represented.';

function prng(seed) {
  let s = seed >>> 0;
  return () => ((s = (s * 1664525 + 1013904223) >>> 0) / 2 ** 32);
}
const pad = (n) => String(n).padStart(2, '0');
/** Wall-clock ISO string without zone (the app rebases all recorded times). */
function iso(date) {
  return `${date.getUTCFullYear()}-${pad(date.getUTCMonth() + 1)}-${pad(date.getUTCDate())}T${pad(date.getUTCHours())}:${pad(date.getUTCMinutes())}:00`;
}
const hoursBefore = (h) => new Date(END.getTime() - h * 3600_000);
const round = (v, d) => Math.round(v * 10 ** d) / 10 ** d;

/** Share of daily use per hour: 90 % between 07:00 and 22:00, 10 % overnight. */
const hourWeight = (hour) => (hour >= 7 && hour < 22 ? 0.9 / 15 : 0.1 / 9);

/**
 * Households (synthetic). occupants and a single optional vulnerability flag are
 * the only household attributes — no names or personal details.
 *   fill / fillHoursAgo : tank % right after the last delivery, and when it happened
 *   intervalDays        : scheduled delivery interval
 */
const HOUSEHOLDS = [
  { id: 'H-012', truck: 'T2', cap: 2000, occ: 5, fill: 96, fillHoursAgo: 27, fillLitres: 1450, interval: 2, pre: 25, anomaly: true },
  { id: 'H-018', truck: 'T1', cap: 2000, occ: 4, fill: 95, fillHoursAgo: 62, fillLitres: 1300, interval: 2, pre: 30 },
  { id: 'H-024', truck: 'T1', cap: 2000, occ: 6, fill: 95, fillHoursAgo: 59, fillLitres: 1500, interval: 2, pre: 20, changedNow: true },
  { id: 'H-031', truck: 'T2', cap: 1500, occ: 4, vulnerability: 'elder', fill: 95, fillHoursAgo: 107, fillLitres: 1150, interval: 4 },
  { id: 'H-037', truck: 'T2', cap: 2000, occ: 7, fill: 95, fillHoursAgo: 90, fillLitres: 1550, interval: 3 },
  { id: 'H-044', truck: 'T3', cap: 2000, occ: 3, fill: 95, fillHoursAgo: 40, fillLitres: 1200, interval: 3, pre: 33, monitorOfflineHours: 5 },
  { id: 'H-050', truck: 'T1', cap: 2300, occ: 5, fill: 97, fillHoursAgo: 14, fillLitres: 1500, interval: 2, pre: 36 },
  { id: 'H-057', truck: 'T3', cap: 2000, occ: 4, fill: 95, fillHoursAgo: 20, fillLitres: 1350, interval: 2, pre: 28, sensorFailure: true },
  { id: 'H-063', truck: 'T2', cap: 2000, occ: 6, vulnerability: 'infant', fill: 96, fillHoursAgo: 22, fillLitres: 1400, interval: 2, pre: 26 },
  { id: 'H-071', truck: 'T1', cap: 1500, occ: 3, fill: 95, fillHoursAgo: 52, fillLitres: 1050, interval: 2, pre: 22 },
  { id: 'H-085', truck: 'T2', cap: 2000, occ: 6, fill: 95, fillHoursAgo: 108, fillLitres: 1600, interval: 4 },
  { id: 'H-092', truck: 'T3', cap: 2000, occ: 4, fill: 95, fillHoursAgo: 26, fillLitres: 1400, interval: 3, pre: 24 },
];

const TANK_HEIGHT_CM = { 1500: 120, 2000: 150, 2300: 165 };

const TRUCKS = [
  { id: 'T1', capacityLitres: 10000, remainingLitres: 7200, trip: 2 },
  { id: 'T2', capacityLitres: 10000, remainingLitres: 6800, trip: 2 },
  { id: 'T3', capacityLitres: 10000, remainingLitres: 9000, trip: 1 },
];

/** Tank % consumed between two times for a household (simple day/night use model). */
function consumedPct(h, fromMs, toMs) {
  const daily = h.occ * LITRES_PER_PERSON_DAY;
  let pct = 0;
  for (let t = fromMs; t < toMs; t += 10 * 60_000) {
    const hour = new Date(t).getUTCHours();
    const dt = Math.min(10 * 60_000, toMs - t) / 3600_000;
    pct += (daily * hourWeight(hour) * dt * 100) / h.cap;
  }
  return pct;
}

function timeline(h, seed) {
  const rand = prng(seed);
  const jitter = (amp) => (rand() * 2 - 1) * amp;
  const fillTime = hoursBefore(h.fillHoursAgo).getTime();
  const baseWater = { turbidity: 0.42, conductivity: 85 + Math.round(jitter(4)), temperature: 14.2 };
  const readings = [];
  const lastIndex = h.monitorOfflineHours ? N - 1 - (h.monitorOfflineHours * 60) / STEP_MIN : N - 1;
  for (let i = 0; i <= lastIndex; i++) {
    const t = new Date(END.getTime() - (N - 1 - i) * STEP_MIN * 60_000);
    const ms = t.getTime();
    const hour = t.getUTCHours() + t.getUTCMinutes() / 60;
    let level;
    let water = { ...baseWater };
    let settle = Infinity;
    if (ms >= fillTime) {
      level = h.fill - consumedPct(h, fillTime, ms);
      settle = (ms - fillTime) / (STEP_MIN * 60_000);
    } else {
      // Before the delivery in the recording: tank drains down to `pre`.
      level = (h.pre ?? 30) + consumedPct(h, ms, fillTime) * 0.98;
    }
    // Freshly delivered water is colder and slightly more turbid; it settles over hours.
    let temperature = Number.isFinite(settle) ? 14.5 - 5 * Math.exp(-settle / 6) : water.temperature;
    temperature += 0.25 * Math.sin(((hour - 15) / 24) * 2 * Math.PI);
    const turbidity = Number.isFinite(settle) ? 0.4 + 0.18 * Math.exp(-settle / 2) : water.turbidity;
    const r = {
      timestamp: iso(t),
      turbidity: round(Math.max(0.05, turbidity + jitter(0.05)), 2),
      conductivity: round(water.conductivity + (Number.isFinite(settle) ? 2 : 0) + jitter(1.2), 0),
      temperature: round(temperature + jitter(0.1), 1),
      tankLevel: round(Math.max(0, Math.min(100, level + jitter(0.15))), 1),
    };
    readings.push(r);
  }
  const at = (hoursAgo) => readings[N - 1 - Math.round((hoursAgo * 60) / STEP_MIN)];
  if (h.anomaly) {
    // A short turbidity episode about 20 hours ago that returns to normal.
    at(20.5).turbidity = 1.92;
    at(20).turbidity = 1.74;
  }
  if (h.changedNow) {
    readings[readings.length - 2].turbidity = 2.08;
    readings[readings.length - 1].turbidity = 2.21;
  }
  if (h.sensorFailure) {
    for (const r of readings.slice(-3)) r.turbidity = null;
  }
  return readings;
}

export function buildAll() {
  const meta = (extra = {}) => ({ synthetic: true, note: SYNTHETIC_NOTE, ...extra });

  const households = {
    _meta: meta({ litresPerPersonPerDay: LITRES_PER_PERSON_DAY }),
    households: HOUSEHOLDS.map((h) => ({
      id: h.id,
      displayName: h.id,
      sensorDevice: `IMQ-${h.id.slice(2).padStart(4, '0')}`,
      // Top-mounted distance sensor geometry (prototype: upright tank, volume ∝ height).
      tankHeightCm: TANK_HEIGHT_CM[h.cap],
      assignedTruck: h.truck,
      tankCapacityLitres: h.cap,
      occupants: h.occ,
      estimatedDailyUseLitres: h.occ * LITRES_PER_PERSON_DAY,
      vulnerability: h.vulnerability || null,
      deliveryIntervalDays: h.interval,
      // Reference "normal" conditions from commissioning; refreshed after each delivery.
      baseline: { turbidity: 0.42, conductivity: 86, temperature: 14.2 },
    })),
  };

  const readings = {
    _meta: meta({ intervalMinutes: STEP_MIN, recordingEnd: iso(END) }),
    households: Object.fromEntries(HOUSEHOLDS.map((h, i) => [h.id, timeline(h, 100 + i)])),
  };

  const deliveries = {
    _meta: meta(),
    deliveries: HOUSEHOLDS.map((h) => ({
      id: `D-SEED-${h.id}`,
      householdId: h.id,
      truckId: h.truck,
      litres: h.fillLitres,
      timestamp: iso(hoursBefore(h.fillHoursAgo)),
    })).sort((a, b) => a.timestamp.localeCompare(b.timestamp)),
  };

  const trucks = { _meta: meta(), trucks: TRUCKS.map((t) => ({ ...t, displayName: `Truck ${t.id}` })) };
  const sensors = {
    _meta: meta(),
    sensors: [
      ...HOUSEHOLDS.map((h, i) => ({
        id: `IMQ-${h.id.slice(2).padStart(4, '0')}`,
        householdId: h.id,
        firmwareVersion: '0.3.1-proto',
        batteryPercent: 96 - ((i * 7) % 23),
      })),
      // A spare, unassigned monitor in municipal stock (for registration/assignment).
      { id: 'IMQ-0100', householdId: null, firmwareVersion: '0.3.1-proto', batteryPercent: 100 },
    ],
  };
  const alerts = { _meta: meta(), alerts: [] };
  const municipality = {
    _meta: meta(),
    community: 'Inukjuak',
    communitySyllabics: 'ᐃᓄᑦᔪᐊᖅ',
    villageWaterCubicMetres: 320,
    villageWaterCapacityCubicMetres: 500,
    maxStopsPerTruckPerDay: 6,
  };

  return {
    'households.json': households,
    'readings.json': readings,
    'deliveries.json': deliveries,
    'trucks.json': trucks,
    'sensors.json': sensors,
    'alerts.json': alerts,
    'municipality.json': municipality,
  };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const root = new URL('../data/', import.meta.url);
  await rm(root, { recursive: true, force: true });
  await mkdir(root, { recursive: true });
  for (const [name, obj] of Object.entries(buildAll())) {
    await writeFile(new URL(name, root), JSON.stringify(obj, null, 2) + '\n');
  }
  console.log('data/ written');
}
